apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yc9kl5dlk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yc9kl5dlk-python 
  name: yc9kl5dlk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yc9kl5dlk-python 
